from AuthX.errors.social import SocialException

__all__ = ["SocialException"]
