exceptioncontext.py,sha256=r5nBxDw5h0nLgz6sCXFwhPK69kOKtnwJOwxdsWvIR30,2146
exceptioncontext-1.0.8.dist-info/LICENSE,sha256=gTW0XSdjEa1mV_oHlGPe72A66yFrkDs4-BFF06W6vbw,671
exceptioncontext-1.0.8.dist-info/METADATA,sha256=mSdJEwB8GFXm6Ji_p-H3BginE7S-iC6REdPtYx44HUc,2192
exceptioncontext-1.0.8.dist-info/WHEEL,sha256=Z-nyYpwrcSqxfdux5Mbn_DQ525iP7J2DG3JgGvOYyTQ,110
exceptioncontext-1.0.8.dist-info/top_level.txt,sha256=fCGjpWqKY0BrfagW2z4p2s5YMthziA0lqb9GOuNqmF0,17
exceptioncontext-1.0.8.dist-info/RECORD,,
